### PR TITLE
Fix text editor example

### PR DESCRIPTION
**Pull request by ttytm**
Uses a simplified prompt for opening a file location (e.g. the V example does).

This removes the need to install the `"github.com/sqweek/dialog"` dependency and works around that the the dialog currently does not open from the callback.

### CODE REVIEW

**Comment by ttytm** [comment]
What I recognized with the Go and V examples, the script embed of the virtual `webui.js` file needs to be done with the leading slash for the text-editor example.
```html
<script src="/webui.js"></script>
```
instead of
```html
<script src="webui.js"></script>
```

I'm adding this as it might be required during the https://github.com/webui-dev/webui/issues/213 fix too.

**Review by hassandraga — APPROVED** [review]

**Comment by hassandraga** [comment]
I will test `prompt'File Location'` because I still confused how it works.
Yes, it should be `"/webui.js"`, while `"webui.js"` will work only if the root folder did not get changed.

**Comment by ttytm** [comment]
I also think there might be more optimal solution that can be used for the text editor example uniformly thought wrappers. I'll have a look how complicated they are before merging this one and update accordingly if it fits.

**Comment by hassandraga** [comment]
We could send raw binary data instead of encoding it... this may be a good optimization.

**Comment by ttytm** [comment]
In the last commit I've added an alternative solution that would fit into the span of this example and supports native file dialogs. But it would become mostly JS. 

It would supports native file dialogs and file reading via the browser using the Web File System API. Basically it utilizes one of the advantages that a browser is used. 

Please let me know if it works for you if you think if it would fit @hassandraga

**Comment by hassandraga** [comment]
The prompt it's not a big deal, at the end of the day WebUI uses web technologies so it's fine.
The problem is it's not supported by Firefox I guess... we should double check.

**Comment by ttytm** [comment]
That's right showOpenFilePicker is not supported by Firefox. Sorry about that. Gonna be fixed 👍

**Comment by hassandraga** [comment]
> Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts)

HTML5 file API will work with Firefox when we implement TLS/SSL in future releases.

**Comment by ttytm** [comment]
It would be great, but I think even with TLS/SSL we would need a workaround for firefox as it doesn't provide support for the method https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker#browser_compatibility.

I added a possible workaround for the example to the main repo that could be used here as well.

**Comment by ttytm** [comment]
Close was accidental. I plan to add another improvement to the C example then it can be used as base for the wrappers.

**Comment by hassandraga** [comment]
Another accidental close?

**Comment by ttytm** [comment]
This time it was intended. It was faster to supersede the PR than to resolve the conflicts.

The commit that closed it: https://github.com/webui-dev/go-webui/commit/8897d1dae460642426800b81986edb6cea0a756d

**Pull request closed without merging**
